# __Problem-1__

In [1]:
import numpy as np

np.random.seed(0)
array = np.random.randint(1, 51, size=(5, 4))
print(array)

anti_diagonal = [array[i, array.shape[1] - 1 - i] for i in range(min(array.shape))]
print(anti_diagonal)

max_in_rows = np.max(array, axis=1)
print(max_in_rows)

overall_mean = np.mean(array)
filtered_elements = array[array <= overall_mean]
print(filtered_elements)

def numpy_boundary_traversal(matrix):
    rows, cols = matrix.shape
    boundary_elements = []
    for col in range(cols):
        boundary_elements.append(matrix[0, col])
    for row in range(1, rows):
        boundary_elements.append(matrix[row, cols - 1])
    if rows > 1:
        for col in range(cols - 2, -1, -1):
            boundary_elements.append(matrix[rows - 1, col])
    if cols > 1:
        for row in range(rows - 2, 0, -1):
            boundary_elements.append(matrix[row, 0])
    return boundary_elements

print(numpy_boundary_traversal(array))


[[45 48  1  4]
 [ 4 40 10 20]
 [22 37 24  7]
 [25 25 13  2]
 [39 40 24 47]]
[np.int32(4), np.int32(10), np.int32(37), np.int32(25)]
[48 40 37 25 47]
[ 1  4  4 10 20 22  7 13  2]
[np.int32(45), np.int32(48), np.int32(1), np.int32(4), np.int32(20), np.int32(7), np.int32(2), np.int32(47), np.int32(24), np.int32(40), np.int32(39), np.int32(25), np.int32(22), np.int32(4)]


# Problem - 2

In [2]:
import numpy as np

np.random.seed(1)
array_1d = np.random.uniform(0, 10, 20)
print(np.round(array_1d, 2))

min_val = np.min(array_1d)
max_val = np.max(array_1d)
median_val = np.median(array_1d)
print(min_val, max_val, median_val)

array_1d[array_1d < 5] = array_1d[array_1d < 5] ** 2
print(np.round(array_1d, 2))

def numpy_alternate_sort(vec):
    sorted_vec = np.sort(vec)
    left = 0
    right = len(sorted_vec) - 1
    result = []
    toggle = True
    while left <= right:
        if toggle:
            result.append(sorted_vec[left])
            left += 1
        else:
            result.append(sorted_vec[right])
            right -= 1
        toggle = not toggle
    return np.array(result)

print(numpy_alternate_sort(array_1d))


[4.17 7.2  0.   3.02 1.47 0.92 1.86 3.46 3.97 5.39 4.19 6.85 2.04 8.78
 0.27 6.7  4.17 5.59 1.4  1.98]
0.0011437481734488664 8.781174363909454 3.7116410063685885
[17.39  7.2   0.    9.14  2.15  0.85  3.47 11.94 15.74  5.39 17.57  6.85
  4.18  8.78  0.08  6.7  17.41  5.59  1.97  3.92]
[1.30815988e-06 1.75724041e+01 7.50080261e-02 1.74143298e+01
 8.52641608e-01 1.73907352e+01 1.97084925e+00 1.57424429e+01
 2.15372915e+00 1.19412216e+01 3.46928663e+00 9.14049845e+00
 3.92442000e+00 8.78117436e+00 4.18007224e+00 7.20324493e+00
 5.38816734e+00 6.85219500e+00 5.58689828e+00 6.70467510e+00]


# Problem - 3

In [4]:
import pandas as pd
import numpy as np

np.random.seed(2)
names = ['Aarav', 'Diya', 'Karan', 'Sneha', 'Rohan', 'Anjali', 'Vikram', 'Pooja', 'Arjun', 'Neha']

subjects = ['Math', 'Science', 'English', 'History', 'Math', 'Science', 'English', 'History', 'Math', 'Science']
scores = np.random.randint(50, 101, size=10)

df = pd.DataFrame({'Name': names, 'Subject': subjects, 'Score': scores, 'Grade': ''})

def assign_grade(score):
    if 90 <= score <= 100:
        return 'A'
    elif 80 <= score <= 89:
        return 'B'
    elif 70 <= score <= 79:
        return 'C'
    elif 60 <= score <= 69:
        return 'D'
    else:
        return 'F'

df['Grade'] = df['Score'].apply(assign_grade)

df_sorted = df.sort_values(by='Score', ascending=False)
print(df_sorted)

avg_scores = df.groupby('Subject')['Score'].mean()
print(avg_scores)

def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]

print(pandas_filter_pass(df))


     Name  Subject  Score Grade
2   Karan  English     95     A
5  Anjali  Science     93     A
8   Arjun     Math     90     A
0   Aarav     Math     90     A
4   Rohan     Math     72     C
6  Vikram  English     68     D
1    Diya  Science     65     D
7   Pooja  History     61     D
3   Sneha  History     58     F
9    Neha  Science     57     F
Subject
English    81.500000
History    59.500000
Math       84.000000
Science    71.666667
Name: Score, dtype: float64
     Name  Subject  Score Grade
0   Aarav     Math     90     A
2   Karan  English     95     A
5  Anjali  Science     93     A
8   Arjun     Math     90     A


# Problem - 4

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

positive_reviews = ["I loved this movie", "Amazing film", "Great acting", "Fantastic story", "Best movie ever", "Highly recommend", "Wonderful experience", "Brilliant direction", "Superb cinematography", "Excellent soundtrack"] * 5
negative_reviews = ["I hated this movie", "Terrible film", "Bad acting", "Awful story", "Worst movie ever", "Do not recommend", "Disappointing experience", "Poor direction", "Lousy cinematography", "Terrible soundtrack"] * 5

reviews = positive_reviews + negative_reviews
sentiments = ["positive"] * 50 + ["negative"] * 50

df = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})

vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(df['Review'])

X_train, X_test, y_train, y_test = train_test_split(X, df['Sentiment'], test_size=0.2, random_state=42)

model = MultinomialNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

def predict_review_sentiment(model, vectorizer, review):
    review_vec = vectorizer.transform([review])
    prediction = model.predict(review_vec)
    return prediction


1.0


# Problem-5

In [2]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_fscore_support

good_feedback = ["Great product", "Very useful", "Highly recommend", "Excellent quality", "Works perfectly", "Satisfied", "Good value", "Will buy again", "Five stars", "Love it"] * 5
bad_feedback = ["Poor quality", "Not useful", "Disappointed", "Waste of money", "Broke quickly", "Bad experience", "Do not recommend", "One star", "Terrible", "Hate it"] * 5

texts = good_feedback + bad_feedback
labels = ["good"] * 50 + ["bad"] * 50

df = pd.DataFrame({'Text': texts, 'Label': labels})

vectorizer = TfidfVectorizer(max_features=300, lowercase=True, stop_words='english')
X = vectorizer.fit_transform(df['Text'])

X_train, X_test, y_train, y_test = train_test_split(X, df['Label'], test_size=0.25, random_state=42)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

precision, recall, f1, _ = precision_recall_fscore_support(y_test, y_pred, average='binary', pos_label='good')
print(precision, recall, f1)

def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)


1.0 0.9285714285714286 0.9629629629629629
